### ISSUE TITLE
Occassional crash

### ISSUE THREAD

**Issue by cdaniel** [cdaniel/atlas2#78]
Tue, 25 Apr 2017 12:32:54 GMT express deprecated res.send(status): Use res.sendStatus(status) instead at src-server/workspace/workspace-router.js:55:22Apr 25, 2017 2:32:54 PM
APP/0 at _combinedTickCallback (internal/process/next_tick.js:67:7)Apr 25, 2017 2:32:54 PM
APP/0 at self.promiseDispatch.done (/home/vcap/app/node_modules/q/q.js:883:30)Apr 25, 2017 2:32:54 PM
APP/0 at /home/vcap/app/src-server/workspace/workspace-router.js:721:19Apr 25, 2017 2:32:54 PM
APP/0 at Object.stringify (native)Apr 25, 2017 2:32:54 PM
APP/0 at ServerResponse.json (/home/vcap/app/node_modules/express/lib/response.js:249:14)Apr 25, 2017 2:32:54 PM
APP/0 at _fulfilled (/home/vcap/app/node_modules/q/q.js:854:54)Apr 25, 2017 2:32:54 PM
APP/0 ^Apr 25, 2017 2:32:54 PM
APP/0 at runSingle (/home/vcap/app/node_modules/q/q.js:137:13)Apr 25, 2017 2:32:54 PM
APP/0 at process._tickCallback (internal/process/next_tick.js:98:9)Apr 25, 2017 2:32:54 PM
APP/0 at stringify (/home/vcap/app/node_modules/express/lib/response.js:1070:12)Apr 25, 2017 2:32:54 PM
APP/0TypeError: Converting circular structure to JSONApr 25, 2017 2:32:54 PM
APP/0 throw e;Apr 25, 2017 2:32:54 PM
APP/0 at flush (/home/vcap/app/node_modules/q/q.js:125:13)Apr 25, 2017 2:32:54 PM
APP/0 at Promise.promise.promiseDispatch (/home/vcap/app/node_modules/q/q.js:816:13)Apr 25, 2017 2:32:54 PM
APP/0 at /home/vcap/app/node_modules/q/q.js:624:44Apr 25, 2017 2:32:54 PM
APP/0/home/vcap/app/node_modules/q/q.js:155Apr 25, 2017 2:32:54 PM
APP/0npm ERR! npm v3.10.9Apr 25, 2017 2:32:54 PM
APP/0npm ERR! node v6.7.0

**Comment by cdaniel** [comment]
Should be fixed with 463d7f9f63e83d7c13c74065bf50ddbe8435d35a
